TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.1
  max_rotational_vel: 0.8
  min_in_place_rotational_vel: 0.3
  escape_vel: -0.4
  
  sim_time: 1.5
  path_distance_bias: 0.8
  goal_distance_bias: 0.7
  vtheta_samples: 50
  occdist_scale: 0.01
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0

  holonomic_robot: false

  